/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package group9.database2;

import static ISITDatabaseRegistry.ISITDatabaseRegistrator.pass;
import static ISITDatabaseRegistry.ISITDatabaseRegistrator.url;
import static ISITDatabaseRegistry.ISITDatabaseRegistrator.user;
import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatMoonlightContrastIJTheme;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 7885425
 */
public class ISITregistration extends javax.swing.JFrame {
public static final String url = "jdbc:mysql://localhost:3306/ISITDatabase";
public static final String user = "root";
String pass = group9login2.pass;
JFrame deletion = new JFrame();
JFrame programexit = new JFrame();
String pwd = "";
int count = 0;
int counter = 0;
int ccounter = 0;
int rcounter = 0;
String condition = "";
Connection cloud9 = null;
PreparedStatement call = null;
ResultSet output = null;
    /**
     * Creates new form ISITregistration
     */
    public ISITregistration() {
        initComponents();
        getmembercount();
        loadloginbase();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("ISIT.png")));
    }
    
public void loadloginbase() {
         try{
        Class.forName("com.mysql.cj.jdbc.Driver");
        cloud9 = DriverManager.getConnection(url, user, pass);
        call = cloud9.prepareStatement("SELECT * FROM member_login");
        output = call.executeQuery();
        ResultSetMetaData getdata = output.getMetaData();
        counter = getdata.getColumnCount();
        DefaultTableModel logintable = new DefaultTableModel();
        logintable.setRowCount(0);
        while (output.next()) {
            Vector cminfo = new Vector();
            for (int c = 1;c<=counter;c++) {
                cminfo.add(output.getObject("Login_ID"));
                cminfo.add(output.getObject("Member_ID"));
                cminfo.add(output.getString("Access_level"));
                cminfo.add(output.getString("username"));
                cminfo.add(output.getString("password"));
            }
            logintable.addRow(cminfo);
            rcounter = logintable.getRowCount();
        rcounter++;
        logid.setText("" +rcounter);
        }
        
         }
         catch (Exception L) {
             JOptionPane.showMessageDialog(null, "LOGIN LOAD ERROR");
         }
}
public void getmembercount() {
     try{
    Class.forName("com.mysql.cj.jdbc.Driver");
    cloud9 = DriverManager.getConnection(url, user, pass);
    call = cloud9.prepareStatement("SELECT * FROM Member_info");
    output = call.executeQuery();
    ResultSetMetaData reqdata = output.getMetaData();
    count = reqdata.getColumnCount();
    
    DefaultTableModel RecordTable = new DefaultTableModel();
    RecordTable.setRowCount(0);
    
        while (output.next())
                {
                 Vector columninfo = new Vector();  
                 
                 for (int m =1; m<=count; m++) {
                     columninfo.add(output.getString("Member_ID"));
                     columninfo.add(output.getString("ID_Number"));
                     columninfo.add(output.getString("Year_Level"));
                     columninfo.add(output.getString("First_Name"));
                     columninfo.add(output.getString("Middle_Name"));
                     columninfo.add(output.getString("Surname"));
                     columninfo.add(output.getString("Gender"));
                     columninfo.add(output.getString("Address"));
                     columninfo.add(output.getString("Birthdate"));
                     columninfo.add(output.getString("PWD"));
                 }
                 RecordTable.addRow(columninfo);
                 
                }
        ccounter = RecordTable.getRowCount();
        ccounter++;
        memid.setText("" +ccounter);
    }
    catch (Exception M) {
        JOptionPane.showMessageDialog(null, "MEMBER COUNT DATABASE CONNECTION ERROR");
    }
     
     
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel28 = new javax.swing.JLabel();
        memid = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        mname = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        lname = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        idnum = new javax.swing.JTextField();
        genderbox = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        yearlevelbox = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        birthday = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        address = new javax.swing.JTextField();
        pwdbox = new javax.swing.JCheckBox();
        registermember = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        exit1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        logid = new javax.swing.JTextField();
        memid1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        userbox = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        registerlogin = new javax.swing.JButton();
        reset1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        passbox = new javax.swing.JPasswordField();
        showpass = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("I.S.I.T MEMBER REGISTRATION");
        getContentPane().setLayout(null);

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("MEMBER ID");
        getContentPane().add(jLabel28);
        jLabel28.setBounds(0, 60, 90, 16);

        memid.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        memid.setForeground(new java.awt.Color(255, 255, 255));
        memid.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        memid.setName(""); // NOI18N
        memid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                memidMouseClicked(evt);
            }
        });
        memid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memidActionPerformed(evt);
            }
        });
        getContentPane().add(memid);
        memid.setBounds(10, 80, 120, 30);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("FIRST NAME");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(130, 60, 90, 16);

        fname.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        fname.setForeground(new java.awt.Color(255, 255, 255));
        fname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnameActionPerformed(evt);
            }
        });
        getContentPane().add(fname);
        fname.setBounds(140, 80, 140, 30);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("MIDDLE NAME");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(290, 60, 90, 16);

        mname.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        mname.setForeground(new java.awt.Color(255, 255, 255));
        mname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        mname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnameMouseClicked(evt);
            }
        });
        mname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnameActionPerformed(evt);
            }
        });
        getContentPane().add(mname);
        mname.setBounds(290, 80, 140, 30);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("LAST NAME");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(430, 60, 90, 16);

        lname.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lname.setForeground(new java.awt.Color(255, 255, 255));
        lname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnameActionPerformed(evt);
            }
        });
        getContentPane().add(lname);
        lname.setBounds(440, 80, 130, 30);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ID NUMBER");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 120, 90, 16);

        idnum.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        idnum.setForeground(new java.awt.Color(255, 255, 255));
        idnum.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        idnum.setName(""); // NOI18N
        idnum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                idnumMouseClicked(evt);
            }
        });
        idnum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idnumActionPerformed(evt);
            }
        });
        getContentPane().add(idnum);
        idnum.setBounds(10, 140, 180, 30);

        genderbox.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        genderbox.setForeground(new java.awt.Color(255, 255, 255));
        genderbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MALE", "FEMALE" }));
        genderbox.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 51, 51)));
        getContentPane().add(genderbox);
        genderbox.setBounds(200, 140, 100, 30);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("GENDER");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(180, 120, 90, 16);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("YEAR LEVEL");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(300, 120, 90, 16);

        yearlevelbox.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        yearlevelbox.setForeground(new java.awt.Color(255, 255, 255));
        yearlevelbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1ST YEAR", "2ND YEAR", "3RD YEAR", "4TH YEAR", "GRADUATED" }));
        yearlevelbox.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 51, 51)));
        getContentPane().add(yearlevelbox);
        yearlevelbox.setBounds(310, 140, 100, 30);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("BIRTHDAY");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(410, 120, 100, 16);

        birthday.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        birthday.setForeground(new java.awt.Color(255, 255, 255));
        birthday.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        birthday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                birthdayActionPerformed(evt);
            }
        });
        getContentPane().add(birthday);
        birthday.setBounds(430, 140, 140, 30);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Ex. \"1999- 07- 14\"");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(410, 170, 170, 20);

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("ADDRESS");
        getContentPane().add(jLabel27);
        jLabel27.setBounds(0, 180, 80, 16);

        address.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        address.setForeground(new java.awt.Color(255, 255, 255));
        address.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressActionPerformed(evt);
            }
        });
        getContentPane().add(address);
        address.setBounds(10, 200, 500, 30);

        pwdbox.setBackground(new java.awt.Color(0, 51, 102));
        pwdbox.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        pwdbox.setForeground(new java.awt.Color(255, 255, 255));
        pwdbox.setText("PWD");
        pwdbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwdboxActionPerformed(evt);
            }
        });
        getContentPane().add(pwdbox);
        pwdbox.setBounds(510, 200, 70, 30);

        registermember.setBackground(new java.awt.Color(0, 255, 0));
        registermember.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        registermember.setForeground(new java.awt.Color(0, 0, 0));
        registermember.setText("REGISTER MEMBER");
        registermember.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 153, 0), new java.awt.Color(0, 102, 0), new java.awt.Color(0, 153, 0), new java.awt.Color(0, 153, 0)));
        registermember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registermemberActionPerformed(evt);
            }
        });
        getContentPane().add(registermember);
        registermember.setBounds(10, 240, 190, 30);

        reset.setBackground(new java.awt.Color(255, 255, 0));
        reset.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        reset.setForeground(new java.awt.Color(0, 0, 0));
        reset.setText("RESET");
        reset.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(204, 204, 0), new java.awt.Color(204, 204, 0), new java.awt.Color(204, 204, 0), new java.awt.Color(204, 204, 0)));
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        getContentPane().add(reset);
        reset.setBounds(220, 240, 170, 30);

        exit1.setBackground(new java.awt.Color(204, 204, 204));
        exit1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        exit1.setForeground(new java.awt.Color(0, 0, 0));
        exit1.setText("BACK");
        exit1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(102, 102, 102), new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153), new java.awt.Color(102, 102, 102)));
        exit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit1ActionPerformed(evt);
            }
        });
        getContentPane().add(exit1);
        exit1.setBounds(410, 240, 160, 30);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("LOGIN ID");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(-10, 290, 90, 16);

        logid.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        logid.setForeground(new java.awt.Color(255, 255, 255));
        logid.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        logid.setName(""); // NOI18N
        logid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logidMouseClicked(evt);
            }
        });
        logid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logidActionPerformed(evt);
            }
        });
        getContentPane().add(logid);
        logid.setBounds(10, 310, 270, 30);

        memid1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        memid1.setForeground(new java.awt.Color(255, 255, 255));
        memid1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        memid1.setName(""); // NOI18N
        memid1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                memid1MouseClicked(evt);
            }
        });
        memid1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memid1ActionPerformed(evt);
            }
        });
        getContentPane().add(memid1);
        memid1.setBounds(290, 310, 280, 30);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("USERNAME:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 340, 80, 16);

        userbox.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        userbox.setForeground(new java.awt.Color(255, 255, 255));
        userbox.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        userbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userboxActionPerformed(evt);
            }
        });
        getContentPane().add(userbox);
        userbox.setBounds(10, 360, 270, 30);

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("PASSWORD:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(290, 340, 80, 20);

        registerlogin.setBackground(new java.awt.Color(0, 255, 0));
        registerlogin.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        registerlogin.setForeground(new java.awt.Color(0, 0, 0));
        registerlogin.setText("REGISTER LOGIN DETAILS");
        registerlogin.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 153, 0), new java.awt.Color(0, 102, 0), new java.awt.Color(0, 153, 0), new java.awt.Color(0, 153, 0)));
        registerlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerloginActionPerformed(evt);
            }
        });
        getContentPane().add(registerlogin);
        registerlogin.setBounds(10, 400, 270, 30);

        reset1.setBackground(new java.awt.Color(255, 255, 0));
        reset1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        reset1.setForeground(new java.awt.Color(0, 0, 0));
        reset1.setText("RESET");
        reset1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(204, 204, 0), new java.awt.Color(204, 204, 0), new java.awt.Color(204, 204, 0), new java.awt.Color(204, 204, 0)));
        reset1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset1ActionPerformed(evt);
            }
        });
        getContentPane().add(reset1);
        reset1.setBounds(290, 400, 280, 30);

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 51, 255));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("I.S.I.T MEMBER REGISTRATION FORM");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(10, 0, 560, 50);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 580, 50);

        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("MEMBER ID");
        jPanel1.add(jLabel30);
        jLabel30.setBounds(280, 290, 90, 16);

        passbox.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        passbox.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(passbox);
        passbox.setBounds(290, 360, 240, 30);

        showpass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/group9/database2/show3.png"))); // NOI18N
        showpass.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 51, 153), new java.awt.Color(0, 51, 153), null, null));
        showpass.setIconTextGap(0);
        showpass.setOpaque(false);
        showpass.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/group9/database2/hide2.png"))); // NOI18N
        showpass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                showpassFocusLost(evt);
            }
        });
        showpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showpassActionPerformed(evt);
            }
        });
        jPanel1.add(showpass);
        showpass.setBounds(530, 360, 38, 31);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 580, 450);

        setBounds(0, 0, 596, 482);
    }// </editor-fold>//GEN-END:initComponents

    private void memidMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_memidMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_memidMouseClicked

    private void memidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_memidActionPerformed

    private void fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnameActionPerformed

    private void mnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnameMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_mnameMouseClicked

    private void mnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnameActionPerformed

    private void lnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lnameActionPerformed

    private void idnumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_idnumMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_idnumMouseClicked

    private void idnumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idnumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idnumActionPerformed

    private void birthdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_birthdayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_birthdayActionPerformed

    private void addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressActionPerformed

    private void pwdboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwdboxActionPerformed
        // TODO add your handling code here:
        if (pwdbox.isSelected()){
            pwd = "TRUE";
        }
        else {
            pwd = "FALSE";
        }
    }//GEN-LAST:event_pwdboxActionPerformed

    private void registermemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registermemberActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            cloud9 = DriverManager.getConnection(url, user, pass);
            call = cloud9.prepareStatement("INSERT INTO Member_info (Member_ID, ID_Number, Year_Level, First_Name, Middle_Name, Surname, Gender, Address, Birthdate, PWD) VALUES( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)");
            call.setString(1, memid.getText());
            call.setString(2, idnum.getText());
            call.setString(3, yearlevelbox.getSelectedItem().toString());
            call.setString(4, fname.getText());
            call.setString(5, mname.getText());
            call.setString(6, lname.getText());
            call.setString(7, genderbox.getSelectedItem().toString());
            call.setString(8, address.getText());
            call.setString(9, birthday.getText());
            call.setString(10, pwd);
            call.executeUpdate();
            JOptionPane.showMessageDialog(null, "MEMBER INFORMATION REGISTERED");
        }
        catch (Exception B) {
            JOptionPane.showMessageDialog(null, "MEMBER INSERT ERROR");
        }
         memid.setText("");
        idnum.setText("");
        yearlevelbox.setSelectedIndex(0);
        fname.setText("");
        mname.setText("");
        lname.setText("");
        genderbox.setSelectedIndex(0);
        birthday.setText("");
        address.setText("");
        pwdbox.setSelected(false);
        loadloginbase();
        getmembercount();
    }//GEN-LAST:event_registermemberActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        memid.setText("");
        idnum.setText("");
        yearlevelbox.setSelectedIndex(0);
        fname.setText("");
        mname.setText("");
        lname.setText("");
        genderbox.setSelectedIndex(0);
        birthday.setText("");
        address.setText("");
        pwdbox.setSelected(false);
        getmembercount();
        loadloginbase();
    }//GEN-LAST:event_resetActionPerformed

    private void exit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit1ActionPerformed
        // TODO add your handling code here:
        programexit = new JFrame("Exit");
        if (JOptionPane.showConfirmDialog(programexit, "GO BACK TO LOG-IN SCREEN?", "PROGRAM", JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){
            try{
                new group9login2().setVisible(true);
                this.setVisible(false);
                
            }
            catch (Exception D) {
                
            }
            
        }
    }//GEN-LAST:event_exit1ActionPerformed

    private void logidMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logidMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_logidMouseClicked

    private void logidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logidActionPerformed

    private void memid1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_memid1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_memid1MouseClicked

    private void memid1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memid1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_memid1ActionPerformed

    private void userboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userboxActionPerformed

    private void registerloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerloginActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            cloud9 = DriverManager.getConnection(url, user, pass);
            call = cloud9.prepareStatement("INSERT INTO Member_login (Login_ID, Member_ID, Access_level, username, password) VALUES (?, ?, ?, ?, ?)");
            call.setString(1, logid.getText());
            call.setString(2, memid1.getText());
            call.setString(3, "MEMBER");
            call.setString(4, userbox.getText());
            call.setString(5, passbox.getText());
            call.executeUpdate();
            JOptionPane.showMessageDialog(null, "LOGIN INFORMATION INSERTED");
          
        }
        catch (Exception C) {
            JOptionPane.showMessageDialog(null, "LOGIN INFO INSERT ERROR");
        }
        loadloginbase();
        getmembercount();
    }//GEN-LAST:event_registerloginActionPerformed

    private void reset1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset1ActionPerformed
        // TODO add your handling code here:
        memid1.setText("");
        logid.setText("");
        userbox.setText("");
        passbox.setText("");
        getmembercount();
        loadloginbase();
    }//GEN-LAST:event_reset1ActionPerformed

    private void showpassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_showpassFocusLost
        // TODO add your handling code here:
        showpass.setSelected(false);
        passbox.setEchoChar('*');
    }//GEN-LAST:event_showpassFocusLost

    private void showpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showpassActionPerformed
        // TODO add your handling code here:
        if (showpass.isSelected())
        {
            passbox.setEchoChar((char)0);
        }
        else {
            passbox.setEchoChar('*');
        }
    }//GEN-LAST:event_showpassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
         try {
             UIManager.setLookAndFeel(new FlatMoonlightContrastIJTheme());    
            }
         catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(group9v2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ISITregistration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address;
    private javax.swing.JTextField birthday;
    private javax.swing.JButton exit1;
    private javax.swing.JTextField fname;
    private javax.swing.JComboBox<String> genderbox;
    private javax.swing.JTextField idnum;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField lname;
    private javax.swing.JTextField logid;
    private javax.swing.JTextField memid;
    private javax.swing.JTextField memid1;
    private javax.swing.JTextField mname;
    private javax.swing.JPasswordField passbox;
    private javax.swing.JCheckBox pwdbox;
    private javax.swing.JButton registerlogin;
    private javax.swing.JButton registermember;
    private javax.swing.JButton reset;
    private javax.swing.JButton reset1;
    private javax.swing.JToggleButton showpass;
    private javax.swing.JTextField userbox;
    private javax.swing.JComboBox<String> yearlevelbox;
    // End of variables declaration//GEN-END:variables
}
